apiVersion: v1
kind: Pod
metadata:
  name: museop-kubia-manual-v2
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
    - image: museopkim/kubia
      name: kubia
      ports:
        - containerPort: 8080
          protocol: TCP
