apiVersion: batch/v1
kind: Job
metadata:
  name: job-activedeadlineseconds
spec:
  backoffLimit: 3
  # Terminating after running completed
  ttlSecondsAfterFinished: 30
  template:
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
        - sleep 60;
      restartPolicy: Never

